services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  StefanFroemken\Mysqlreport\:
    resource: '../Classes/*'

  StefanFroemken\Mysqlreport\Menu\Page:
    public: true
    shared: false

  StefanFroemken\Mysqlreport\Menu\PageFinder:
    public: true
