services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  StefanFroemken\Mysqlreport\:
    resource: '../Classes/*'

  StefanFroemken\Mysqlreport\Domain\Factory\PanelFactory:
    public: true

  StefanFroemken\Mysqlreport\Domain\Model\Page:
    public: true
